[package]
name = "todo_in_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-sgr-macros = "0.1.0"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.118"
toml = "0.8.14"

[env]
json_file_path = "TodoList.json"
